Feature/min-473 Collect user data and provide it to FE
minterest-finance/web2.0 pull request #3
Opened 2021-07-19 08:59 UTC by gavrilin-remote

Collect user data from rpc once per day. Save that data to db, provide graphql interface to get this data.

2021-07-27 16:48 UTC, kurotych requested changes
Why have you added DS files to repositories?

2021-07-27 16:48 UTC, kurotych commented on packages/data-collector/src/config/common.config.ts
> +            type: 'BlockNumber',
I see that getUserData rpc accepts blockHash, not blockNumber 
https://github.com/minterest-finance/minterest-chain-node/blob/development/pallets/controller/rpc/src/lib.rs#L218

Please check

2021-07-27 16:48 UTC, kurotych commented on packages/db-layer/src/db/models/user.data.model.ts
> +    net_apy: { type: String, required: false },
Could you write documentation for this parameters?

2021-07-27 16:48 UTC, kurotych commented on packages/data-collector/src/controllers/insolvency.controller.ts
> +      await switchOnInsolvencyNotification(user);
I'm not sure about this. 
As i see you will send notifications to user when you can't receive total-collateral and borrowed from database.
is it appropriate behavior?

2021-07-27 16:48 UTC, kurotych commented on packages/db-layer/src/db/services/user.data.service.ts
> +export const getUserData = async (
Could you write more detailed documentation?
Also, I can't understand why get* function calls upsert*

2021-07-28 11:14 UTC, kurotych requested changes

2021-07-28 11:14 UTC, kurotych commented on packages/data-collector/src/controllers/user.controller.ts
> +      total_borrow_in_usd: userDataResponse.total_borrow_in_usd.toString(),
Where will we use these two parameters?

2021-07-29 10:34 UTC, gavrilin-remote commented on packages/data-collector/src/config/common.config.ts
> +            type: 'BlockNumber',
https://minterestfinance.atlassian.net/wiki/spaces/MINTEREST/pages/134807557/Minterest+API#getUserData(account_id:-AccountId,-blockNumber?:-BlockNumber):-Option%3CUserData%3E

I'm make it based on documentation.

2021-07-29 10:40 UTC, kurotych commented on packages/data-collector/src/config/common.config.ts
> +            type: 'BlockNumber',
In code I see that it is BlockHash required. Could you check it by sending rpc with second parameter and fix documentation if it required. Thanks

2021-07-29 10:46 UTC, gavrilin-remote commented on packages/data-collector/src/controllers/insolvency.controller.ts
> +      await switchOnInsolvencyNotification(user);
the method "switchOnInsolvencyNotification" switch on flag in db, that indicate - send notification for user if its insolvency rate will more than 0.8 next time.
So the current behavior:
User's insolvency rate up to 0.85 - send notification and switch off the flag.
User's insolvency rate up to 0.86 - don't send notification since flag is false.
User's insolvency rate down to 0.5 - switch on the flag.
User's insolvency rate up to 0.9 - send notification and switch off the flag.
User's total_borrow or total_supply become 0 - switch on the flag.

2021-07-29 10:50 UTC, gavrilin-remote commented on packages/db-layer/src/db/services/user.data.service.ts
> +export const getUserData = async (
The users of chain not duplicated in web2.0 db. So, web2.0 creating user in db anytime user will interact with chain-node or web2.0 through frontend app. That the reason to use upsert, this method will not increase load to the db.

2021-07-29 10:57 UTC, gavrilin-remote commented on packages/data-collector/src/controllers/user.controller.ts
> +      total_borrow_in_usd: userDataResponse.total_borrow_in_usd.toString(),
I'm not totally sure which data we will use in future, so for now I'm just saving everything that backend return for me.

2021-07-29 11:38 UTC, gavrilin-remote commented on packages/data-collector/src/config/common.config.ts
> +            type: 'BlockNumber',
Updated

2021-07-30 08:25 UTC, kurotych approved these changes

2021-07-30 09:20 UTC, merged